app/_bokeh/views.py
# root/app/_bokeh/views.py

from flask import Blueprint, request, render_template, flash, redirect, \
url_for, jsonify
from flask_login import login_required, current_user

from app.utils.decorators import check_confirmed
from app.utils.token import confirm_token
from app.models import User, Device, Calibration, Measure
from app._bokeh import forms
from app import db, app

from bokeh.embed import autoload_server
from urllib import urlencode
from sqlalchemy import desc
import json, uuid, datetime


mod = Blueprint('bokeh', __name__,
    template_folder='templates',
    static_folder='static')


def get_user_from(token):
    token_dict = confirm_token(token)
    if isinstance(token_dict, dict) and 'id' in token_dict:
        return User.query.filter_by(id=uuid.UUID(token_dict['id'])).first()
    return None


def get_devices_from(user):
    if user.using_devices:
        _using_devices = [uuid.UUID(key) for key,val in user.using_devices.iteritems()]
        return db.session.query(
                    Device.id,
                    Device.code
                ).\
                filter(Device.id.in_(_using_devices)).\
                all()
    return None


def get_calibrations_from(user):
    if user.using_devices:
        _using_devices = [uuid.UUID(key) for key,val in user.using_devices.iteritems()]
        return  db.session.query(
                    Calibration.id.label('c_id'),
                    Calibration.device_id.label('d_id'),
                    Device.code.label('d_code'),
                    Calibration.data.label('c_data')
                ).\
                distinct(Calibration.device_id).\
                join(Calibration.device).\
                filter(Calibration.device_id.in_(_using_devices)).\
                order_by(Calibration.device_id, Calibration.created_on.desc()).\
                all()
    return None


def get_measurement_from(user):
    return  db.session.query(
                Device.code.label('d_code'),
                Calibration.data.label('c_data'),
                Measure.data.label('m_data'),
                Measure.created_on.op('AT TIME ZONE')('UTC').label('m_date'),
                Measure.id
            ).\
            join(Measure.device).\
            join(Measure.calibration).\
            filter_by(created_by = user.id).\
            order_by(Measure.created_on.desc()).\
            limit(5).\
            all()


@mod.route('/home/')
@mod.route('/', alias=True)
@login_required
@check_confirmed
def index():
    return redirect(url_for('.devices'))


@mod.route('/devices/', methods=['GET', 'POST'])
@login_required
@check_confirmed
def devices():
    form = forms.DeviceForm(request.form)
    if form.validate_on_submit():
        device = Device.query.filter_by(code=form.device_code.data).first()
        if not device:
            device = Device(code = form.device_code.data)
            db.session.add(device)
            db.session.commit()

        if form.use_device.data:
            if current_user.using_devices is None:
                current_user.using_devices = {str(device.id): str(datetime.datetime.utcnow())}
            else:
                _len = len(current_user.using_devices)
                if _len >= 5:
                    _using_devices = sorted(current_user.using_devices.items(), key=lambda x: x[1], reverse=True)
                    for i in _using_devices[4:]:
                        current_user.using_devices.pop(i[0], None)

                current_user.using_devices[str(device.id)] = str(datetime.datetime.utcnow())

            db.session.add(current_user)
            db.session.commit()

        elif current_user.using_devices.pop(str(device.id), None):
            db.session.add(current_user)
            db.session.commit()
    else:
        forms.flash_errors(form)

    return render_template("_bokeh/devices.html", form=form, devices=get_devices_from(current_user))


@mod.route('/get_devices/<token>/')
def get_devices(token):
    user = get_user_from(token)
    if user and user.has_valid_token(token, token_type='bokeh'):
        devices = get_devices_from(user)
        if devices:
            response = dict()
            for row in devices:
                for key in row.keys():
                    if not key in response: response[key] = []
                    response[key].append(getattr(row, key))

            return jsonify(response)

    flash("The token used here may be invalid or expired, "
          "or you have not registered any device to use.", 'danger')
    return 'not_ok'


@mod.route('/calibration/')
@login_required
@check_confirmed
def calibration():
    token = current_user.generate_token(
        expiration = app.config['TOKEN_EXPIRES_IN'],
        token_type = 'bokeh'
    )
    _request = urlencode(dict(token=token))
    script   = autoload_server(model=None, app_path="/_calibre", request=_request)
    return render_template('_bokeh/base_bokeh.html', bokeh_script=script)


@mod.route('/save_calibration/<token>/', methods=['POST'])
def save_calibration(token):
    user = get_user_from(token)
    if user and user.has_valid_token(token, token_type='bokeh'):
        _data = request.get_json(force=True)
        if 'lin' in _data and 'ang' in _data and 'd_id' in _data:
            calibration = Calibration(
                device_id = _data['d_id'],
                data = dict(
                    linear  = _data['lin'],
                    angular = _data['ang'],
                ),
                created_by = user.id,
                updated_by = user.id,
            )
            db.session.add(calibration)
            db.session.commit()

            # Calibration successfully saved
            return 'successfully_saved'

    # The token used here may be invalid or expired,
    # or the data to save may be corrupted
    return 'saving_error'


@mod.route('/get_calibrations/<token>/')
def get_calibrations(token):
    user = get_user_from(token)
    if user and user.has_valid_token(token, token_type='bokeh'):
        calibrations = get_calibrations_from(user)
        if calibrations:
            response = dict()
            for row in calibrations:
                for key in row.keys():
                    if not key in response: response[key] = []
                    response[key].append(getattr(row, key))

            return jsonify(response)

    flash("The token used here may be invalid or expired, "
          "or you have not registered any device to use.", 'danger')
    return 'not_ok'


@mod.route('/measurement/')
@login_required
@check_confirmed
def measurement():
    token = current_user.generate_token(
        expiration = app.config['TOKEN_EXPIRES_IN'],
        token_type = 'bokeh'
    )
    _request = urlencode(dict(token=token))
    script   = autoload_server(model=None, app_path="/_measure", request=_request)
    return render_template('_bokeh/base_bokeh.html', bokeh_script=script)


@mod.route('/save_measurement/<token>/', methods=['POST'])
def save_measurement(token):
    user = get_user_from(token)
    if user and user.has_valid_token(token, token_type='bokeh'):
        _data = request.get_json(force=True)
        if 'f' in _data and 't' in _data and \
        'd_id' in _data and 'c_id' in _data:
            measure = Measure(
                device_id      = _data['d_id'],
                calibration_id = _data['c_id'],
                data = dict(
                    force = _data['f'],
                    time  = _data['t'],
                ),
                created_by = user.id,
                updated_by = user.id,
            )
            db.session.add(measure)
            db.session.commit()

            # Measurement successfully saved
            return 'successfully_saved'

    # The token used here may be invalid or expired,
    # or the data to save may be corrupted
    return 'saving_error'


@mod.route('/get_measurement/<token>/')
def get_measurement(token):
    user = get_user_from(token)
    if user and user.has_valid_token(token, token_type='bokeh'):
        measurements = get_measurement_from(user)
        if measurements:
            response = dict()
            for row in measurements:
                for key in row.keys():
                    if not key in response: response[key] = []
                    response[key].append(getattr(row, key))

            return jsonify(response)

    flash("The token used here may be invalid or expired, "
          "or there is no measurement saved.", 'danger')
    return 'not_ok'


@mod.route('/plot_measures/')
@login_required
@check_confirmed
def plot_measures():
    token = current_user.generate_token(
        expiration = app.config['TOKEN_EXPIRES_IN'],
        token_type = 'bokeh'
    )
    _request = urlencode(dict(token=token))
    script   = autoload_server(model=None, app_path="/_plot", request=_request)
    return render_template('_bokeh/base_bokeh.html', bokeh_script=script)

app/templates/_macros.html
{% macro render_field(field, placeholder=None, glyphicon=None, glyphpos="") %}
    <div id="div-{{field.id }}" class="form-group {{ glyphpos }}">
        {{ field.label(class="sr-only") }}
        {% if glyphicon %}
            <span class="glyphicon {{ glyphicon }}"></span>
        {% endif %}
        {% set css_class = 'form-control ' + kwargs.pop('class', '') %}
        {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
    </div>
{% endmacro %}

{% macro input(name, value='', type='text') -%}
    <input type="{{ type }}" value="{{ value|e }}" name="{{ name }}">
{%- endmacro %}

{%- macro textarea(name, value='', rows=10, cols=40) -%}
    <textarea name="{{ name }}" rows="{{ rows }}" cols="{{ cols
        }}">{{ value|e }}</textarea>
{%- endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>{% block title %}{% endblock %}</title>

        <!-- meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{% block description %}{% endblock %}">
        <meta name="author" content="{% block author %}{% endblock %}">

        <!-- styles -->
        <link href="{{ url_for('static', filename='vendor/css/bootstrap.min.css') }}" rel="stylesheet" media="screen">
        <link href="{{ url_for('static', filename='vendor/css/font-awesome.min.css') }}" rel="stylesheet" media="screen">
        <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" media="screen">
        <!-- <link href="url_for('static', filename='img/favicon.ico')" rel="icon"> -->
        {% endblock %}
    </head>
    <body>
        {% include "navigation.html" %}

        <div id="header">
            {% block header %}{% endblock %}
        </div>

        <div id="container" class="container-fluid">
            <!-- child template -->
            {% block container %}{% endblock %}

            {% block messages %}
                {% include "messages.html" %}
            {% endblock %}
        </div>

        {% block footer %}
        <!-- <footer id="footer" class="container-fluid text-center">
            <p>Footer Text</p>
        </footer> -->
        {% endblock %}

        <!-- scripts -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{{ url_for('static', filename='vendor/js/jquery-3.1.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendor/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
        {% block js_script %}{% endblock %}
    </body>
</html>

app/templates/messages.html
<!-- messages -->
{% with messages = get_flashed_messages(with_categories=true) %}
    <!-- Categories:
        success (green),
        info    (blue),
        warning (yellow),
        danger  (red) -->
{% if messages %}
    <div class="row flash_msg">
        <div class="col-md-6 col-md-offset-3">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                {{message}}
            </div>
            {% endfor %}
        </div>
    </div>
{% endif %}
{% endwith %}

<!-- errors -->
{% if error %}
<p class="error"><strong>Error:</strong> {{ error }}</p>
{% endif %}

app/templates/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top my-navbar" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" id="navbar-toggle" class="navbar-toggle"
            data-toggle="collapse" data-target="#topnav" aria-expanded="false"
            aria-controls="#topnav">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-navicon"></i>
            </button>

            {% set blueprint = request.url_rule.endpoint %}
            {% if (blueprint.split('.')[0] == "bokeh" and current_user.is_authenticated
               and current_user.confirmed) %}
            <button type="button" id="sidebar-toggle" class="navbar-toggle visible-xs"
            data-toggle="collapse" data-target="#sidebar" aria-expanded="false"
            aria-controls="#sidebar">
                <span class="sr-only">Toggle side navigation</span>
                <i class="fa fa-dashboard"></i>
            </button>
            {% endif %}

            <a class="navbar-brand" href="{{ url_for('bokeh.index') }}">
                <i class="nav-icon fa fa-home"></i> Home
            </a>
        </div>

        <div class="collapse navbar-collapse topnav" id="topnav">
            <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
                {% if current_user.confirmed %}
                <li class="{{ 'active' if blueprint == 'user.my_info' }}">
                    <a href="{{ url_for('user.my_info') }}">
                        <i class="nav-icon fa fa-vcard"></i> My Info
                    </a>
                </li>
                <li class="{{ 'active' if blueprint == 'user.request_change_email' }}">
                    <a href="{{ url_for('user.request_change_email') }}">
                        <i class="nav-icon fa fa-envelope"></i> Email
                    </a>
                </li>
                <li class="{{ 'active' if blueprint == 'user.change_password' }}">
                    <a href="{{ url_for('user.change_password') }}">
                        <i class="nav-icon fa fa-user-secret"></i> Password
                    </a>
                </li>
                {% else %}
                <li class="{{ 'active' if blueprint == 'user.unconfirmed' }}">
                    <a href="{{ url_for('user.unconfirmed') }}">
                        <i class="nav-icon fa fa-check-square-o"></i> Confirm
                    </a>
                </li>
                {% endif %}
                <li class="{{ 'active' if blueprint == 'user.logout' }}">
                    <a href="{{ url_for('user.logout') }}">
                        <i class="nav-icon fa fa-sign-out"></i> Logout
                    </a>
                </li>
            {% else %}
                <li class="{{ 'active' if blueprint == 'user.login' }}">
                    <a href="{{ url_for('user.login') }}">
                        <i class="nav-icon fa fa-sign-in"></i> Login
                    </a>
                </li>
                <li class="{{ 'active' if blueprint == 'user.register' }}">
                    <a href="{{ url_for('user.register') }}">
                        <i class="nav-icon fa fa-user-plus"></i> Sign up
                    </a>
                </li>
            {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>